import {readFileSync} from "node:fs";
import {describe, expect, it} from "vitest";

import unoConfig from "../uno.config";
import {CONTROLS, DESIGN_PAGE, SECTIONS, THEMING, TOKEN_ROLES} from "../src/content/design";
import {
    AGENT_DROPS, AGENT_SECTIONS, CANONICAL_SECTIONS, GUARDRAILS_HEADING, renderDesignDoc,
} from "../src/lib/design-doc";
import {ICON_IDS, iconClass} from "../src/lib/icons";
import {PALETTE} from "../src/lib/palette";
import {pageCss} from "./helpers/css";
import {classTokens} from "./helpers/pages";

/**
 * THE PALETTE IS PUBLISHED SOMEWHERE THIS SUITE CANNOT SEE, AND THIS IS THE HALF THAT CAN.
 *
 * The site's design vocabulary — fifteen theme tokens, a short type ramp, three controls —
 * is synced to a design tool, where an agent builds screens out of it. That export is a
 * SNAPSHOT: it is generated by a converter that runs by hand, against the built site, and
 * nothing about editing this repository re-runs it. So the failure mode is not a bad
 * export. It is a good export going quietly out of date the moment a token is renamed here.
 *
 * The division of labour is the one `tests/dns-config.test.ts` argues for, and neither half
 * is redundant:
 *
 *   - The CONVERTER proves the export can be built and is internally consistent. It needs
 *     the design tool's own toolchain and a network round trip, so it runs when somebody
 *     syncs, and never in CI.
 *   - THIS half proves the shipped files still say what the export claims about them, and
 *     it runs in `pnpm test` on every pull request — including the ones that touch nothing
 *     under `.design-sync/`. That is the whole point: the way this breaks is an edit to
 *     `src/layouts/BasicLayout.astro`, and nothing in the sync directory would notice.
 *
 * WHAT IS ASSERTED, AND WHY EACH ONE IS HERE. `.design-sync/conventions.md` is the document
 * handed to the design agent as the system's own description of itself. Every name in it
 * was checked by hand once, at sync time, against a build that no longer exists. These
 * gates are that check made repeatable:
 *
 *   1. The two themes define the SAME tokens. This is a source-of-truth invariant that
 *      owes nothing to the sync — a token added to light and forgotten in dark resolves to
 *      nothing for every reader on the other theme, and no other gate here looks.
 *   2. The document's token table and the built stylesheet name the same set, BOTH ways. A
 *      one-way check would let the table quietly shrink.
 *   3. The classes the document promises are present really are; the one it warns is
 *      ABSENT really is. That warning is the document's most load-bearing sentence — a
 *      shortcut composed into others is not itself emitted, so an agent that believed
 *      otherwise would write markup that silently does nothing.
 *
 * It reads the built page rather than the source, through `pageCss`, because the export is
 * built from the same artifact: what ships is what the agent gets.
 *
 * WHAT CHANGED WHEN `/design` ARRIVED, because two of the gates below now point somewhere
 * else. The document stopped being hand-written: it is RENDERED from `src/content/design.ts`
 * and held against the committed copy by a file snapshot, so the question "does the markdown
 * still say what the code says" collapses into "was the file regenerated". That moves the
 * gated source one level up — the token gate reads the MODULE against the stylesheet now,
 * rather than the markdown table against the stylesheet, because the table is no longer a
 * place anyone can type into. The chain is: stylesheet defines, module names, document and
 * page render. Each link has an assertion here, and the middle one is the only one a person
 * edits.
 *
 * THE SNAPSHOT IS THE LEGITIMATE FORM OF A COMMITTED GENERATED FILE, and the distinction is
 * the whole reason four generated HTML reference cards were retired rather than kept:
 * `dns/requirements.txt` is compiled from `dns/requirements.in` and a gate fails when the two
 * disagree, where `public/preview.jpg` is a render of a card with nothing watching and has
 * gone stale silently twice. `pnpm test:update` regenerates; drift fails `pnpm test`.
 */

const CONVENTIONS = ".design-sync/conventions.md";
const conventions = () => readFileSync(CONVENTIONS, "utf8");

/** The `/design` page, as the build emits it. */
const DESIGN_PAGE_FILE = "dist/design/index.html";

/**
 * THE PAGE AS TEXT, NORMALISED ONCE FOR EVERY GATE BELOW THAT READS IT.
 *
 * Two things stand between a string authored in `src/content/design.ts` and the same string in
 * the built page, and neither is a reason to loosen a needle into a substring — a loosened needle
 * is how a gate starts passing on content that is wrong:
 *
 *   - THE PAGE IS HTML, so an apostrophe ships as a numeric entity. That is not hypothetical and
 *     it is not confined to the guidance lines: several roles in `TOKEN_ROLES` carry one, so the
 *     control-and-token gate would fail on CORRECT content without this. The entities are decoded
 *     here, which normalises the HAYSTACK — the needle is compared as the module authored it.
 *   - ASTRO MAY SPLIT A TEXT NODE, so one authored sentence can arrive broken across an element
 *     boundary. Tags are removed rather than replaced with a space, which rejoins a split word;
 *     runs of whitespace then collapse, so a line the markup wrapped still matches the single-line
 *     string it came from. Needles are collapsed the same way for the same reason.
 *
 * Attribute values go with the tags they sit in, which is the direction that matters: a needle
 * found only in a `content=` or a `style=` would be a false pass rather than a rendered line.
 */
const decodeEntities = (text: string) => text
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code: string) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&quot;/g, "\"")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");

/** One authored line and its rendering differ by whitespace alone once the markup is gone. */
const collapsed = (text: string) => text.replace(/\s+/g, " ").trim();

const designPageText = () =>
    collapsed(decodeEntities(readFileSync(DESIGN_PAGE_FILE, "utf8").replace(/<[^>]*>/g, "")));

/**
 * EVERY ELEMENT ON THE BUILT PAGE WEARING ONE OF THESE CLASSES IS ONE ROW OF SOMETHING.
 *
 * The page sets every string a reader is meant to copy — a token name, a class name, a mark's
 * name, and a value — in the hairline box `.design-name` draws. Reducing a row to that list is
 * what lets a gate ask about ONE row rather than about the document, and comparing by EQUALITY
 * rather than by substring is what keeps `--sport-ride` out of `--sport-ride-on-ink`'s row.
 * Astro scopes with a `data-astro-cid-…` attribute rather than an extra class, so the class
 * attribute is matched as authored.
 *
 * THE PALETTE IS DRAWN IN TWO SHAPES NOW AND BOTH ARE ROWS. Plan 042 took the three neutrals
 * out of the sheet — each is within one step of the plate it would have been drawn on, in both
 * themes, so three swatches published three rectangles nobody could tell apart — and redrew
 * them as one nested specimen whose labels are `.design-stack-line`. The other twelve are
 * `.design-ledger-row`. A gate that knew only about the sheet would go quietly vacuous for the
 * three, which is exactly the failure this file's own header describes one level up.
 */
const rowLiterals = (rowClass: string) => {
    const html = readFileSync(DESIGN_PAGE_FILE, "utf8");
    const row = new RegExp(`<(\\w+) class="[^"]*\\b${rowClass}\\b[^"]*"[^>]*>([\\s\\S]*?)</\\1>`, "g");
    return [...html.matchAll(row)].map((match) =>
        [...match[2]!.matchAll(/<span class="[^"]*\bdesign-name\b[^"]*"[^>]*>([\s\S]*?)<\/span>/g)]
            .map((box) => collapsed(decodeEntities(box[1]!.replace(/<[^>]*>/g, "")))));
};

/** The two shapes the palette is drawn in, as one list of rows. See {@link rowLiterals}. */
const paletteRowLiterals = () => [...rowLiterals("design-ledger-row"), ...rowLiterals("design-stack-line")];

/** Every line of a section a reader is meant to be able to find, wherever it is rendered. */
const sectionLines = (section: typeof SECTIONS[keyof typeof SECTIONS]) =>
    [section.heading, section.lede, ...section.does, ...section.donts];

/**
 * THE SPEC AT THE REPOSITORY ROOT, which is the same bytes as `/design.md` on the web.
 *
 * `DESIGN.md` is a generated file that is COMMITTED, which this repository allows in exactly one
 * shape: compiled from a named source with a gate that fails when the two disagree — the shape
 * `dns/requirements.txt` has, and the opposite of `public/preview.jpg`, which is a render of a
 * card with nothing watching and has gone stale silently twice. `pnpm test:update` regenerates;
 * drift fails `pnpm test`.
 *
 * The name is not this repository's choice. The `improve` pipeline these plans implement globs
 * for it by name during recon and carries what it finds into the plans it writes, and the
 * DESIGN.md format is an open convention for exactly this document — so a file called anything
 * else would be a file nothing looks for.
 */
const DESIGN_DOC = "DESIGN.md";

/**
 * THE BUDGET, AND IT IS NOT THIS REPOSITORY'S NUMBER.
 *
 * `.design-sync/conventions.md` is prepended to a generated README through the `readmeHeader`
 * key and inlined into the SYSTEM PROMPT of a design agent that gets that README and the bound
 * artifacts and nothing else. The design-sync skill states the preamble budget as two to four
 * thousand characters; this is the top of that range, so it is a ceiling rather than a target.
 *
 * WHY IT IS ASSERTED AND NOT WRITTEN DOWN IN PROSE. The document is generated, so its length is
 * a function of a module anybody may edit — and the failure mode is silent: a longer preamble
 * still renders, still matches its own committed copy, and simply spends more of a context
 * window that belongs to somebody else. The previous hand-written document was already over
 * this line, and the generated one that replaced it was nearly twice it.
 *
 * WHAT TO DO WHEN THIS GOES RED: drop something from the AGENT audience in
 * `src/lib/design-doc.ts`, never from `src/content/design.ts` — the full rendering carries the
 * module whole, and trimming the module would take the guidance off `/design` and out of
 * `DESIGN.md` to buy room in a third document. Record the trade in `.design-sync/NOTES.md`.
 */
const AGENT_BUDGET = 4096;

/** Every `--token: value` declared under a `:root[data-theme=…]` block in the built CSS. */
function themeTokens(css: string): Record<string, Set<string>> {
    const themes: Record<string, Set<string>> = {};
    for (const m of css.matchAll(/:root\[data-theme=['"]?(\w+)['"]?\]\s*\{([^}]*)\}/g)) {
        const names = [...m[2]!.matchAll(/(--[\w-]+)\s*:/g)].map((d) => d[1]!);
        if (!names.length) continue;
        themes[m[1]!] ??= new Set();
        for (const n of names) themes[m[1]!]!.add(n);
    }
    return themes;
}

describe("the design system this site publishes", () => {
    const css = pageCss();
    const themes = themeTokens(css);

    it("defines both themes, from the built page", () => {
        expect(Object.keys(themes).sort(),
            "the theme blocks moved or changed shape — every assertion below would be vacuous")
            .toEqual(["dark", "light"]);
        expect(themes.light!.size,
            "no tokens parsed out of the light theme — the gates below would assert nothing")
            .toBeGreaterThan(10);
    });

    it("gives every token a value in BOTH themes", () => {
        const light = [...themes.light!].sort(), dark = [...themes.dark!].sort();
        expect(dark.filter((t) => !themes.light!.has(t)),
            "these are defined in dark and not in light, so they resolve to nothing in light")
            .toEqual([]);
        expect(light.filter((t) => !themes.dark!.has(t)),
            "these are defined in light and not in dark, so they resolve to nothing in dark")
            .toEqual([]);
    });

    /**
     * THE MODULE IS THE GATED SOURCE NOW, not the markdown table.
     *
     * This used to read `.design-sync/conventions.md`'s table, because that table was where a
     * person typed a token's name. It is generated from `TOKEN_ROLES` today, so reading it
     * here would ask the same question one level too far downstream: the snapshot below
     * already proves the table IS the module, and a gate that checks a rendering of a list
     * against the stylesheet cannot say which of the two is wrong when they disagree.
     *
     * BOTH DIRECTIONS, for the reason the old note gave: a one-way check lets the list
     * quietly shrink. A token defined in the layout and never named here is one no designer
     * and no agent will ever reach for; a token named here that the stylesheet no longer
     * defines sends both of them at something that resolves to nothing.
     */
    it("names every token the stylesheet defines, and no other", () => {
        const named = new Set(TOKEN_ROLES.map((t) => t.token));
        expect(named.size, "TOKEN_ROLES is empty — this gate would assert nothing")
            .toBe(TOKEN_ROLES.length);
        const defined = themes.light!;
        expect([...defined].filter((t) => !named.has(t)).sort(),
            "src/content/design.ts gives these tokens no role, so nothing that reads it will reach for them")
            .toEqual([]);
        expect([...named].filter((t) => !defined.has(t)).sort(),
            "src/content/design.ts names these and the built stylesheet does not define them")
            .toEqual([]);
    });

    it("ships the classes that document promises are present", () => {
        const doc = conventions();
        const promised = doc.match(/Guaranteed present: ([^.]+)\./s)?.[1];
        expect(promised, `${CONVENTIONS} no longer carries its "Guaranteed present" list`).toBeTruthy();
        const names = [...promised!.matchAll(/`([a-z][\w-]*)`/g)].map((m) => m[1]!);
        expect(names.length, "no class names parsed out of that list — this gate would be vacuous")
            .toBeGreaterThan(3);
        expect(names.filter((n) => !css.includes(`.${n}{`)),
            `${CONVENTIONS} promises these classes and the built stylesheet has no rule for them`)
            .toEqual([]);
    });

    /**
     * THE DOCUMENT NAMES THE SURFACES IT SAYS ARE ABSENT, AND EVERY ONE OF THEM MUST BE. This
     * used to assert a single hand-written sentence in `src/lib/design-doc.ts` — "`control-
     * surface` is not in the stylesheet" — which was fine while the site had one base. It has
     * two now, and a gate keyed on one class name would have certified a document that had
     * silently stopped mentioning the other.
     *
     * SO IT READS THE CLAIM RATHER THAN A LITERAL. The warning lives in the module's own
     * controls guidance, is rendered into BOTH audiences, and names its surfaces in prose; this
     * pulls every `*-surface` token out of that sentence and holds each against the shipped
     * sheet. A surface added to `uno.config.ts` and left out of the guidance is caught by the
     * floor below rather than passing unnoticed, which is the direction that matters — the
     * failure being guarded is a base class that starts shipping a rule nothing wears, and a
     * document that goes on saying it does not.
     */
    it("keeps every surface that document warns is absent absent", () => {
        const warning = SECTIONS.controls.donts.find((line) => line.includes("-surface"));
        expect(warning, "the controls guidance no longer warns about a surface class at all")
            .toBeDefined();
        const named = [...warning!.matchAll(/\b([a-z][\w-]*-surface)\b/g)].map((m) => m[1]!);
        expect(new Set(named).size, "no surface class parsed out of that warning — this gate would be vacuous")
            .toBeGreaterThan(1);
        for (const surface of new Set(named)) {
            expect(conventions(), `${CONVENTIONS} does not carry the warning about \`${surface}\``)
                .toContain(surface);
            expect(css.includes(`.${surface}{`),
                `\`${surface}\` now ships a rule, so the warning in ${CONVENTIONS} is false`)
                .toBe(false);
        }
        // Both bases really are shortcuts in the config, so the sentence is about something.
        const shortcuts = Object.keys(unoConfig.shortcuts as Record<string, string>);
        expect([...new Set(named)].filter((s) => !shortcuts.includes(s)),
            "the guidance warns about a surface that is not a shortcut at all").toEqual([]);
    });

    /**
     * EACH COMMITTED DOCUMENT IS THE RENDERING, and this is what makes that checkable rather
     * than a convention. Edit a role in `src/content/design.ts` and these go red until
     * `pnpm test:update` rewrites the files; edit a file by hand and it goes red until the
     * edit is moved into the module. Both directions are the point — the second one is what
     * `.design-sync/NOTES.md` used to have to ask for in prose.
     *
     * TWO SNAPSHOTS OF ONE RENDERER, and the pair is the whole reason `renderDesignDoc` takes an
     * audience instead of there being two functions. A second renderer would drift from the
     * first in silence: both would still render, and both would still match their own committed
     * copy, because a snapshot only ever compares a document with itself.
     */
    it("is the module, rendered — the agent's document has no second author", async () => {
        await expect(renderDesignDoc("agent")).toMatchFileSnapshot(`../${CONVENTIONS}`);
    });

    it("is the module, rendered in full — the repository's spec has no second author", async () => {
        await expect(renderDesignDoc("full")).toMatchFileSnapshot(`../${DESIGN_DOC}`);
    });

    /**
     * THE BUDGET IS THE ONE PROPERTY THE SNAPSHOT ABOVE CANNOT SEE. A document twice its size
     * matches its own committed copy perfectly; the cost lands in a context window belonging to
     * a design agent that never gets to complain. See `AGENT_BUDGET` for where the number comes
     * from and for what to do when this goes red.
     */
    it("keeps the agent's preamble inside the budget it is inlined into", () => {
        const rendered = renderDesignDoc("agent");
        expect(rendered.length,
            `the agent rendering is ${rendered.length} characters against a ${AGENT_BUDGET} budget. It is `
            + `inlined into a design agent's system prompt, so this is somebody else's context window `
            + `being spent. Drop something from the "agent" audience in src/lib/design-doc.ts — never `
            + `from src/content/design.ts, which the full rendering carries whole — and record the `
            + `trade in .design-sync/NOTES.md`)
            .toBeLessThanOrEqual(AGENT_BUDGET);
    });

    /**
     * THE AGENT CANNOT OPEN THIS REPOSITORY, so a path into it is not a weak pointer — it is a
     * dead end dressed as an instruction. That agent "gets the README and the bound artifacts,
     * nothing else", which is why the closed-set section sends it to the stylesheet it was handed
     * rather than to the layout the tokens are actually declared in.
     *
     * THE FULL RENDERING IS ASSERTED IN THE OPPOSITE DIRECTION in the same breath, because a
     * predicate that only ever says "no" is satisfied by an empty string. Its readers both have
     * this tree open — one is reading `DESIGN.md` in a checkout, the other fetched `/design.md`
     * from a site whose source is public — so pointing at a file is the useful thing to do, and a
     * full rendering that had stopped doing it would be the same defect from the other side.
     */
    it("sends the agent to the bundle and the checkout reader to the tree", () => {
        expect(renderDesignDoc("agent"),
            "the agent rendering names a path in this repository, which its reader has no copy of")
            .not.toMatch(/\bsrc\//);
        expect(renderDesignDoc("full"),
            "the full rendering names no path in this repository, so it tells a reader holding the "
            + "checkout nothing about where any of this is written down")
            .toMatch(/\bsrc\//);
    });

    /**
     * NEITHER RENDERING MAY GO EMPTY, which is the one way a snapshot can be passed by a document
     * that says nothing: delete the body, run `pnpm test:update`, and both files agree perfectly
     * with a renderer that produces two headings. So each is asked for the thing it exists to
     * carry — every token the module names — and the two are asked separately, because they are
     * two audiences and a union would let either one shrink to nothing behind the other.
     */
    it("carries every token the module names, in both renderings", () => {
        expect(TOKEN_ROLES.length, "TOKEN_ROLES is empty — this gate would assert nothing")
            .toBeGreaterThan(5);
        for (const audience of ["full", "agent"] as const) {
            const rendered = renderDesignDoc(audience);
            expect(rendered.length, `the ${audience} rendering is empty`).toBeGreaterThan(500);
            expect(TOKEN_ROLES.map(({token}) => token).filter((t) => !rendered.includes(t)),
                `the ${audience} rendering does not name these tokens, so whatever reads it cannot `
                + "reach for them").toEqual([]);
        }
    });

    /**
     * A HEADING WITH NOTHING UNDER IT IS THE ONE FAILURE THE SNAPSHOT CANNOT SEE, because an
     * empty list renders as an empty list and matches its own committed copy perfectly. The
     * guidance is the half of this module a design agent actually acts on, so a section that
     * has stopped carrying any is worth more than a heading that has gone missing.
     */
    it("gives every section guidance on both sides", () => {
        const sections = Object.entries(SECTIONS);
        expect(sections.length, "SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        for (const [key, section] of sections) {
            expect(section.does.length, `SECTIONS.${key} tells nobody what to do`).toBeGreaterThan(0);
            expect(section.donts.length, `SECTIONS.${key} tells nobody what not to do`).toBeGreaterThan(0);
            expect(section.heading.trim().length, `SECTIONS.${key} has no heading`).toBeGreaterThan(0);
            expect(section.lede.trim().length, `SECTIONS.${key} has no lede`).toBeGreaterThan(0);
        }
    });

    /**
     * THE RAMP ON THE PAGE IS A CENSUS AND THIS IS ITS GATE.
     *
     * `src/pages/design.astro` has to write its type steps out as literal class names, because
     * UnoCSS only emits a rule for a name it can see literally in a file it scans and it does
     * not scan `.ts` — the same fact the icon safelist exists for. A written-out list is a
     * second copy of a set the stylesheet already owns, so it needs the thing every other
     * census in this repository has: something that reddens when the two disagree.
     *
     * ASKED IN THE DIRECTION THAT CAN ACTUALLY BE WRONG. A step the page shows and no other
     * page uses is not a defect — the page is a legitimate wearer, and its own use is what
     * puts the rule in the sheet. A step some OTHER page wears and this one omits is a
     * styleguide that has quietly stopped describing the site, and that is what this catches.
     */
    /**
     * THE CENSUS IS COMPLETE, WHICH IS A STRONGER CLAIM THAN THE SAFELIST EVER NEEDED.
     *
     * `ICON_IDS` exists so `uno.config.ts` can emit a rule for every mark that is computed at
     * render time. That job never required it to be exhaustive: the theme toggle writes its
     * sun and moon out as literal class names, UnoCSS extracts them by itself, and the
     * safelist was complete without them for as long as nothing else read it.
     *
     * `/design` reads it, and reads it as "the marks a designer may reach for" — so the list
     * has to answer a question it was never asked before. Measured before this gate went in:
     * the page rendered 16 of the 18 marks the build ships and the generated document told a
     * design agent that 16 was the whole set. Both halves are asserted here, because either
     * one alone permits the defect: a mark in the sheet and not in the census is a mark
     * nothing describes, and a mark in the census with no rule is the zero-size mask box the
     * safelist exists to prevent.
     */
    /**
     * THE THEME NAMES ARE THE ONE VALUE THIS MODULE RESTATES, so they are gated rather than
     * trusted.
     *
     * `THEMING.themes` exists because both surfaces need the legal set: `/design` renders the
     * line matching the live theme and hides the other, and the generated document lists both
     * for an agent that has neither. The names themselves belong to
     * `src/layouts/BasicLayout.astro`, which is where the two `:root[data-theme=…]` blocks are
     * — so this list is a second home, and a second home nothing checks is the exact defect
     * this whole suite exists for.
     *
     * BOTH DIRECTIONS. A theme in the stylesheet and not in this list is a page that would
     * render NO example line for a reader in it; a theme in the list and not in the stylesheet
     * is a value the document tells a designer to write that resolves to nothing.
     */
    it("names every theme the stylesheet defines, and no other", () => {
        const declared = Object.keys(themes).sort();
        expect(declared.length, "no theme blocks parsed — this gate would assert nothing")
            .toBeGreaterThan(1);
        expect([...THEMING.themes].sort(),
            "src/content/design.ts's theme list and the built stylesheet's theme blocks disagree, so "
            + "/design would render the wrong example line — or none at all — for a reader in the "
            + "theme it has forgotten")
            .toEqual(declared);
        expect(THEMING.example.includes("{theme}"),
            "THEMING.example lost its {theme} placeholder, so both surfaces would print it literally")
            .toBe(true);
    });

    it("names every mark the build ships, and no mark the build does not", () => {
        const shipped = new Set([...css.matchAll(/\.(i-[a-z0-9-]+)/g)].map((m) => m[1]!));
        expect(shipped.size, "no icon rules parsed out of the stylesheet — this gate would be vacuous")
            .toBeGreaterThan(5);
        const census = new Set(ICON_IDS.map(iconClass));
        expect([...shipped].filter((c) => !census.has(c)).sort(),
            "the stylesheet ships these marks and ICON_IDS does not name them, so /design and the "
            + "document generated from it both understate what a designer may reach for")
            .toEqual([]);
        expect([...census].filter((c) => !shipped.has(c)).sort(),
            "ICON_IDS names these and the stylesheet has no rule for them — a presetIcons class with "
            + "no rule renders as a mask box at zero size")
            .toEqual([]);
    });

    /**
     * A SECTION MAY NOT REACH ONE SURFACE AND NOT THE OTHERS, and until these five gates that was
     * the ordinary outcome rather than a corner case. Both directions were measured by mutation
     * before they went in, and both were silent:
     *
     *   - A fifth entry added to `SECTIONS` shipped on `/design` and appeared in NONE of the three
     *     documents. `pnpm test` stayed green and `pnpm test:update` had nothing to rewrite,
     *     because `renderFull()` hand-listed four keys and never rendered it.
     *   - The page's section loop filtered one key out, and the built page shipped with no Marks
     *     section while every document went on carrying it. `pnpm test` stayed green again.
     *
     * The file snapshots above cannot see either one — a snapshot only ever compares a document
     * with itself, which is the same reasoning this suite's header gives for a different failure.
     * So each surface is asked, separately, for the strings the module authored.
     *
     * ASSERTED AS STRINGS RATHER THAN AS A COUNT, for the reason the token gate above gives: a
     * count is satisfied by one heading swapped for another.
     */
    it("renders every section the module holds into the full spec", () => {
        const sections = Object.entries(SECTIONS);
        expect(sections.length, "SECTIONS is empty — this gate would assert nothing")
            .toBeGreaterThan(0);
        const rendered = renderDesignDoc("full");
        for (const [key, section] of sections) {
            expect(sectionLines(section).filter((line) => !rendered.includes(line)),
                `the full rendering is missing these lines of SECTIONS.${key}, so DESIGN.md and `
                + "/design.md describe a design system that is not the one /design shows")
                .toEqual([]);
        }
    });

    /**
     * THE FORMAT'S ONE HARD ERROR, AND THE CHEAPEST GATE IN THIS FILE.
     *
     * Everything else the DESIGN.md format asks for is tolerated when it is missing — its own
     * "Consumer Behavior for Unknown Content" preserves an unknown heading rather than rejecting
     * it, which is exactly why this document drifted for as long as it did with nothing
     * complaining. A DUPLICATE `##` heading is the exception: the format says reject the file.
     *
     * IT IS HERE BECAUSE THE LINTER IS NOT. Nothing in `pnpm test` runs `@google/design.md`, and
     * wiring it in would pin a dependency on somebody else's release cadence for one assertion.
     * This is that assertion, written against the rendering rather than the file, so it fails on
     * the change rather than on the regeneration.
     *
     * THE MAPPING IS WHAT MAKES IT REACHABLE. Before the canonical headings, every heading came
     * straight off a distinct `SECTIONS` key and a collision took two authored strings being
     * typed the same. Now a mapping target can collide with another target, or with an authored
     * heading it does not replace, and neither is visible at the site the edit is made.
     */
    it("gives the full rendering no heading twice, which the format rejects a file for", () => {
        const headings = [...renderDesignDoc("full").matchAll(/^## (.+)$/gm)].map((m) => m[1]!);
        expect(headings.length, "no ## headings parsed out of the full rendering — this gate would "
            + "be vacuous, and the parse is what it rests on").toBeGreaterThan(3);
        const seen = new Set<string>();
        expect(headings.filter((h) => seen.size === seen.add(h).size),
            "the full rendering emits these headings more than once. A duplicate section heading "
            + "is the DESIGN.md format's only hard error — a consumer rejects the whole file — so "
            + "DESIGN.md and /design.md would be unreadable to everything that reads them by "
            + "format rather than as prose").toEqual([]);
    });

    /**
     * THE CONTENT MODULE CALLS A SECTION WHAT THE FORMAT CALLS IT, AND SO DOES EVERY SURFACE.
     *
     * These two headings were the site's own British words, and the full rendering swapped in the
     * format's names on its way out — so `/design` said `Colour` where `DESIGN.md` said `Colors`.
     * That is a design system nobody can quote consistently, and it is what this gate replaced the
     * mapping with: the module authors `Colors`, every rendering carries it unchanged, and the
     * agreement is asserted rather than performed.
     *
     * IT IS NOT A TAUTOLOGY, WHICH THE MAPPING'S ORDER GATE WAS. `CANONICAL_SECTIONS` and
     * `SECTIONS` are two different homes, so the mutation that matters — renaming a heading back in
     * `src/content/design.ts`, which is an ordinary-looking edit to page copy — moves ONE of them
     * and reddens this. The old gate could only ever catch a renderer that stopped consulting a
     * table; nothing could catch the content module walking away from the format.
     *
     * BOTH DIRECTIONS, AND OVER THE RENDERING AS WELL AS THE MODULE. The module agreeing is what
     * makes the surfaces agree, but the document is what a consumer reads, so the heading is
     * asserted where it is DRAWN (`## Colors`) and exactly once — the format's one hard error is a
     * duplicate section heading, and a second gate above owns that in general.
     */
    it("calls every section the format names by the format's own name, in the module and the document", () => {
        expect(CANONICAL_SECTIONS.length,
            "CANONICAL_SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        const rendered = renderDesignDoc("full");
        for (const [key, canonical] of CANONICAL_SECTIONS) {
            expect(SECTIONS[key].heading,
                `src/content/design.ts heads SECTIONS.${key} "${SECTIONS[key].heading}" where the `
                + `DESIGN.md format calls that section "${canonical}". The page, the spec and the `
                + "agent's brief all render this string, so they would disagree about what one "
                + "section is called — which is the drift the canonical names exist to end")
                .toBe(canonical);
            expect(rendered.split("\n").filter((line) => line === `## ${canonical}`).length,
                `the full rendering does not head SECTIONS.${key} "${canonical}" exactly once, so a `
                + "consumer looking for the format's own section finds arbitrary prose instead")
                .toBe(1);
        }
    });

    /**
     * THE AGGREGATED GUARDRAILS CARRY EVERY LINE, KEYED BY THE SECTION THEY CAME FROM.
     *
     * That section is the format's canonical place for guidance, and for a consumer reading only
     * the canonical sections it is the only place: every line this system has is authored under a
     * heading the format has never heard of. So the aggregation dropping one is a line that
     * reaches a human reading `/design` and reaches that consumer not at all — and it would be
     * invisible, because a document with a shorter list still matches its own committed copy.
     *
     * THE KEYING IS ASSERTED WITH THE LINE RATHER THAN BESIDE IT. A bullet that carried the
     * guidance without naming its section would be ambiguous in exactly the way an aggregation
     * needs not to be — a reader meeting "let a labeled control wrap" here has no way back to the
     * paragraph that says why — so the needle is the section's heading and the line on ONE line of
     * output.
     *
     * AND EACH LIST MUST LAND UNDER ITS OWN SUBHEADING. The section is drawn the way the format's
     * own examples draw it: `### Do` and `### Don't` under `## Do's and Don'ts`. A do rendered
     * beneath the don'ts is the one corruption that reads as correct — same words, same bullet,
     * inverted meaning — so the two groups are located and asserted separately rather than the
     * whole section being searched for each line.
     */
    it("aggregates every section's guidance into the format's guardrail section", () => {
        const rendered = renderDesignDoc("full");
        const body = rendered.split(`## ${GUARDRAILS_HEADING}\n`)[1];
        expect(body, `the full rendering has no "${GUARDRAILS_HEADING}" section — the DESIGN.md `
            + "format's canonical guardrails, and the one section a consumer reads for them")
            .toBeTruthy();

        // Each subheading's own block: from its `###` to the next one, or to the end.
        const block = (label: string) => {
            const at = body!.indexOf(`### ${label}\n`);
            expect(at, `the guardrail section has no "### ${label}" subheading — the shape the `
                + "DESIGN.md format's own examples draw this section in").toBeGreaterThan(-1);
            const rest = body!.slice(at + `### ${label}\n`.length);
            const next = rest.indexOf("\n### ");
            return (next < 0 ? rest : rest.slice(0, next)).split("\n");
        };
        const groups: [string, string[], (s: typeof SECTIONS[keyof typeof SECTIONS]) => readonly string[]][] = [
            [DESIGN_PAGE.does_label, block(DESIGN_PAGE.does_label), (s) => s.does],
            [DESIGN_PAGE.donts_label, block(DESIGN_PAGE.donts_label), (s) => s.donts],
        ];

        const sections = Object.entries(SECTIONS);
        expect(sections.length, "SECTIONS is empty — this gate would assert nothing")
            .toBeGreaterThan(0);
        for (const [label, lines, pick] of groups) {
            expect(lines.filter((l) => l.startsWith("- ")).length,
                `no bullets parsed under "### ${label}" — this half of the gate would be vacuous`)
                .toBeGreaterThan(0);
            for (const [key, section] of sections) {
                const named = section.heading;
                expect(pick(section).filter((line) => !lines.some((l) => l.includes(named) && l.includes(line))),
                    `these ${label} lines of SECTIONS.${key} do not reach the "### ${label}" half of `
                    + `the aggregated "${GUARDRAILS_HEADING}" section under the name "${named}", so a `
                    + "consumer that reads the format's canonical guardrails and nothing else either "
                    + "never sees them or reads them as the opposite instruction").toEqual([]);
            }
        }
    });

    /**
     * THE DOCUMENT SPELLS THE FORMAT'S OWN NOUNS THE FORMAT'S WAY.
     *
     * THIS IS NOT A RULE ABOUT BRITISH VERSUS AMERICAN ENGLISH, and framing it that way was the
     * first mistake here — it produced a forty-word spelling list that had nothing to do with the
     * format and would have reddened one day on a correct sentence. The rule is narrower and it
     * follows from compliance: the DESIGN.md format OWNS a handful of nouns. `colors` is a
     * front-matter token group and `Colors` is a canonical section name. `Typography` is both.
     * Where the format has named a thing, this document has to call it that, because a reader who
     * greps `## Colors` or resolves `{colors.light-accent}` is using the format's spelling and
     * gets nothing back for a near-miss.
     *
     * SO THE POPULATION IS THE FORMAT'S NOUNS, NOT THE ENGLISH LANGUAGE. Everything else in this
     * repository — every comment, `CLAUDE.md`, every other page of the site — is the site's own
     * voice and nothing here looks at it. A word is in this list only because the format itself
     * uses it.
     *
     * ASKED OF WHAT SHIPS. Both renderings and the built page, so it cannot be satisfied by
     * editing the content module while a string authored in the renderer still says the other
     * thing — which is exactly the split that let the page and the document disagree before.
     */
    it("spells the format's own nouns the format's way, on every surface", () => {
        // Each entry: a noun the DESIGN.md format names, and the variants that are not it. Both
        // halves are the format's business — `colors` is its token group and `Colors` its section.
        const FORMAT_NOUNS: [string, string[]][] = [
            ["colors", ["colour", "colours", "coloured", "colouring", "recolour", "recoloured"]],
            ["behavior", ["behaviour", "behavioural"]],
        ];
        const surfaces: [string, string][] = [
            ["the full rendering (DESIGN.md and /design.md)", renderDesignDoc("full")],
            ["the agent's brief (.design-sync/conventions.md)", renderDesignDoc("agent")],
            [DESIGN_PAGE_FILE, designPageText()],
        ];
        for (const [where, text] of surfaces) {
            expect(text.length, `nothing read out of ${where} — this gate would be vacuous`)
                .toBeGreaterThan(1000);
            for (const [noun, variants] of FORMAT_NOUNS) {
                expect(variants.filter((w) => new RegExp(`\\b${w}\\b`, "i").test(text)),
                    `${where} spells "${noun}" another way. The DESIGN.md format names that noun `
                    + "itself — as a token group, a section, or both — and this document claims "
                    + "that format, so a consumer greping the format's own word finds nothing. Fix "
                    + "it where the string is AUTHORED: src/content/design.ts for anything a "
                    + "section carries, src/lib/design-doc.ts for a rendering's own framing")
                    .toEqual([]);
            }
        }
    });

    /**
     * EVERY TOKEN REFERENCE IN THE PROSE RESOLVES, WHICH IS A HARD ERROR IN THE FORMAT.
     *
     * The format's reference syntax is `{group.token}` and its own words are that a reference
     * pointing at a key that is not there is a broken-ref error. The front matter's two aliases
     * already throw at render time if their target leaves the stylesheet; the PROSE had no such
     * protection, and prose is where a reference is most likely to rot — a token renamed in
     * `src/layouts/BasicLayout.astro` moves the front matter with it automatically, because that
     * is derived, and leaves every sentence citing the old name behind.
     *
     * PARSED OUT OF THE RENDERED DOCUMENT AND RESOLVED AGAINST ITS OWN FRONT MATTER, so this asks
     * the shipped artifact rather than the module. A reference the document defines nowhere is
     * exactly what a consumer would reject the file for.
     */
    it("resolves every token reference its own prose makes", () => {
        const rendered = renderDesignDoc("full");
        const matter = rendered.split("---")[1];
        expect(matter, "the full rendering has no front matter to resolve references against")
            .toBeTruthy();
        const defined = new Set([...matter!.matchAll(/^ {2}([a-z0-9-]+):/gim)].map((m) => m[1]!));
        expect(defined.size, "no token keys parsed out of the front matter — this gate would be "
            + "vacuous").toBeGreaterThan(5);

        const body = rendered.slice(rendered.indexOf("\n# "));
        const refs = [...body.matchAll(/\{([a-z]+)\.([a-z0-9-]+)\}/gi)];
        expect(refs.length, "the prose makes no token references at all — the format's own examples "
            + "cite tokens inline, and this gate would be vacuous").toBeGreaterThan(0);
        expect(refs.filter((m) => !defined.has(m[2]!)).map((m) => m[0]),
            "these token references in the prose point at keys the front matter does not define. "
            + "A reference to a missing key is a broken-ref error in the DESIGN.md format, so the "
            + "whole file is rejected — cite a token that exists, or stop citing one")
            .toEqual([]);
        expect(refs.filter((m) => m[1]!.toLowerCase() !== "colors").map((m) => m[0]),
            "these token references name a group this document does not publish. Only `colors` is "
            + "in the front matter; every other group is declared omitted with a reason, so a "
            + "reference into one resolves to nothing")
            .toEqual([]);
    });

    /**
     * THE SECTIONS THE FORMAT NAMES APPEAR IN THE ORDER THE FORMAT SEQUENCES THEM.
     *
     * The spec's words are that sections which are present "should appear in the sequence listed",
     * and nothing in this repository held that — the document was in the module's key order, which
     * happened to agree and had no reason to keep agreeing. Reordering `SECTIONS` is an ordinary
     * edit to `/design`; it must not be able to silently un-sequence a document claiming a format.
     *
     * RELATIVE POSITIONS RATHER THAN FIXED INDICES, so a section added anywhere — mapped or not —
     * does not redden this. What is asserted is the only thing the format actually asks for.
     *
     * WHAT THIS CAN AND CANNOT KNOW, said plainly because the difference is easy to misread. The
     * table's own order is the renderer's input, so the first assertion holds the RENDERER to the
     * declaration — measured: a renderer that stops calling `sectionOrder` reddens it. It does NOT
     * hold the declaration to the spec, and nothing offline can: whether `Colors` really precedes
     * `Typography` in v0.4.0 is a fact about somebody else's document, which the linter and the
     * `spec` subcommand answer and this suite deliberately does not depend on. Re-deriving it here
     * would be paraphrasing that spec into this repository, which is the copy that goes stale in
     * silence.
     *
     * THE OTHER TWO ASSERTIONS OWE THE TABLE NOTHING, which is why they are here. That every
     * canonically named section precedes every unknown one, and that the guardrails come last, are
     * the format's own shape rather than this table's contents — so a `sectionOrder` that
     * interleaved them, or a document that ended on something else, is red however the table is
     * written.
     */
    it("sequences the format's own sections the way the format sequences them", () => {
        expect(CANONICAL_SECTIONS.length,
            "CANONICAL_SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        const headings = [...renderDesignDoc("full").matchAll(/^## (.+)$/gm)].map((m) => m[1]!);
        const canonical = CANONICAL_SECTIONS.map(([, name]) => name);
        const positions = canonical.map((name) => headings.indexOf(name));
        expect(positions.filter((p) => p < 0),
            "a canonical heading is not in the full rendering at all — the gate above says which")
            .toEqual([]);
        expect(positions, "the DESIGN.md format's own sections are out of its sequence in the full "
            + `rendering. The order it wants is ${canonical.join(", ")}, and this document emits `
            + headings.join(", "))
            .toEqual([...positions].sort((a, b) => a - b));

        // The format sequences its own sections first and its guardrails last, and both of those
        // are true of the format rather than of the table above — an unknown heading is preserved
        // wherever it sits, so the only place it may NOT sit is in front of a section the format
        // named and sequenced itself.
        //
        // ASKED OF THE MODULE'S SECTIONS RATHER THAN OF EVERY HEADING, which is the difference
        // between a semantic predicate and a carve-out. Two headings in this document are not
        // `SECTIONS` entries at all — the Overview, and the theming block that travels with it
        // because it is the precondition every sentence after it depends on — and naming either
        // one here as an exception would be a list that the next such block is quietly missing
        // from. Deriving the population from `SECTIONS` excludes both for the reason they are
        // excluded, and reads the heading straight off the module now that the module authors the
        // format's own names.
        const unnamed = (Object.keys(SECTIONS) as (keyof typeof SECTIONS)[])
            .map((key) => SECTIONS[key].heading)
            .filter((h) => !canonical.includes(h));
        expect(unnamed.filter((h) => headings.indexOf(h) < Math.max(...positions)),
            "these sections the DESIGN.md format has no name for are emitted in among the ones it "
            + "names and sequences. The format preserves an unknown heading anywhere, so they "
            + "belong after the sequence rather than inside it").toEqual([]);
        expect(headings.at(-1), `"${GUARDRAILS_HEADING}" is the last section the format sequences, `
            + "and this document ends on another one").toBe(GUARDRAILS_HEADING);
    });

    /**
     * THE SAME QUESTION ASKED OF THE BUILT PAGE, which is the direction the renderer cannot fix:
     * a section dropped from `src/pages/design.astro` leaves every document intact and the page
     * silently smaller. See `designPageText` for why the haystack is normalised and the needle
     * never is.
     */
    it("renders every section the module holds onto the page", () => {
        const sections = Object.entries(SECTIONS);
        expect(sections.length, "SECTIONS is empty — this gate would assert nothing")
            .toBeGreaterThan(0);
        const page = designPageText();
        expect(page.length, `no text parsed out of ${DESIGN_PAGE_FILE} — this gate would be vacuous`)
            .toBeGreaterThan(1000);
        for (const [key, section] of sections) {
            expect(sectionLines(section).map(collapsed).filter((line) => !page.includes(line)),
                `${DESIGN_PAGE_FILE} does not carry these lines of SECTIONS.${key}, so the page `
                + "and the documents rendered from the same module disagree about what this "
                + "design system says")
                .toEqual([]);
        }
    });

    /**
     * THE AGENT AUDIENCE CARRIES WHAT IT DECLARES AND NOTHING IT DOES NOT, both directions in one
     * breath. Its subset is deliberate — that reader is paying for every character out of a system
     * prompt — so the gate above cannot be asked of it. What can be asked is that the declaration
     * in `src/lib/design-doc.ts` and the document it produces have not quietly stopped agreeing.
     *
     * THE HEADING AS THE DOCUMENT DRAWS IT, not as a bare word. The negative half of a two-way
     * assertion is the half that reddens on correct content when the needle is loose: "Type" as a
     * substring would fail the day any sentence in that document used the word.
     */
    it("carries exactly the sections the agent audience declares", () => {
        expect(AGENT_SECTIONS.length, "AGENT_SECTIONS is empty — this gate would assert nothing")
            .toBeGreaterThan(0);
        const rendered = renderDesignDoc("agent");
        const drawn = (key: keyof typeof SECTIONS) => `## ${SECTIONS[key].heading}`;
        expect(AGENT_SECTIONS.filter((key) => !rendered.includes(drawn(key))),
            "src/lib/design-doc.ts declares the agent rendering carries these sections and the "
            + "document it renders has no heading for them")
            .toEqual([]);
        const keys = Object.keys(SECTIONS) as (keyof typeof SECTIONS)[];
        expect(keys.filter((key) => !AGENT_SECTIONS.includes(key) && rendered.includes(drawn(key))),
            "the agent rendering carries these sections and declares that it does not, so the "
            + "recorded reason for dropping them is describing a document that no longer exists")
            .toEqual([]);
    });

    /**
     * EVERY SECTION IS SOMEBODY'S DECISION. A key that is neither carried by the agent audience nor
     * recorded as dropped is a section nobody decided about, and that is the state the whole of
     * this block exists to make impossible — it is also the one the fifth-section mutation now
     * lands in, since the full rendering iterates and the page always did.
     */
    it("accounts for every section in the agent audience, carried or dropped for a reason", () => {
        const keys = Object.keys(SECTIONS) as (keyof typeof SECTIONS)[];
        expect(keys.length, "SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        expect(keys.filter((key) => !AGENT_SECTIONS.includes(key) && !(key in AGENT_DROPS)),
            "nothing in src/lib/design-doc.ts says whether the agent rendering carries these "
            + "sections. Add the key to AGENT_SECTIONS, or to AGENT_DROPS with the reason")
            .toEqual([]);
        expect(AGENT_SECTIONS.filter((key) => key in AGENT_DROPS),
            "these sections are declared carried AND recorded as dropped, so one of the two lists "
            + "is describing a document that does not exist")
            .toEqual([]);
        for (const [key, reason] of Object.entries(AGENT_DROPS)) {
            expect(reason.trim().length,
                `AGENT_DROPS.${key} records no reason, which is the implicit drop this list `
                + "replaced rather than a recorded one")
                .toBeGreaterThan(20);
        }
    });

    /**
     * THE PAGE SHOWS EVERY CONTROL AND EVERY TOKEN ROLE THE MODULE NAMES. The section gate above
     * walks `SECTIONS`, and these two lists are the specimens beside them — hand-placed on
     * `src/pages/design.astro`, one block per kind, rather than looped like the sections. A
     * control published in the module and left off the page is a kind a designer reading the site's
     * own styleguide will never meet; a token role is the same failure one level down.
     */
    it("shows every control and every token role the module names", () => {
        expect(CONTROLS.length, "CONTROLS is empty — this gate would assert nothing")
            .toBeGreaterThan(1);
        expect(TOKEN_ROLES.length, "TOKEN_ROLES is empty — this gate would assert nothing")
            .toBeGreaterThan(5);
        const page = designPageText();
        expect(page.length, `no text parsed out of ${DESIGN_PAGE_FILE} — this gate would be vacuous`)
            .toBeGreaterThan(1000);
        expect(CONTROLS.map(({name}) => name).filter((name) => !page.includes(name)),
            `${DESIGN_PAGE_FILE} draws no specimen named for these kinds of control, so the site's `
            + "own styleguide publishes fewer kinds than the module does")
            .toEqual([]);
        expect(TOKEN_ROLES.flatMap(({token, role}) => [token, collapsed(role)])
            .filter((line) => !page.includes(line)),
            `${DESIGN_PAGE_FILE} does not carry these token names or roles, so a designer reading `
            + "the page cannot reach for what the documents tell them exists")
            .toEqual([]);
    });

    /**
     * EVERY TOKEN'S ROW CARRIES THAT TOKEN'S OWN TWO VALUES — asked PER ROW, and that is the
     * load-bearing half of this gate rather than a nicety.
     *
     * A document-wide substring test is not the property, because THIS PALETTE REUSES VALUES
     * HEAVILY: measured as it stands, the two theme blocks declare thirty values over only
     * fourteen distinct ones, and the most-worn of those is the value of eight different tokens.
     * So "both of this token's values appear somewhere in the page" stays green for most tokens
     * with BOTH of their own cells missing, because another token supplies the string. Measured
     * by rotating every row's value cells onto its neighbour — every value still present
     * document-wide, and this went red naming twenty-nine of the thirty. Do not simplify it back.
     *
     * VERBATIM, NOT NORMALISED, AND THE ASYMMETRY WITH `tests/palette.test.ts` IS DELIBERATE.
     * That suite compares against the minified STYLESHEET, where the value is a declaration the
     * minifier lower-cases and folds; these are page TEXT and ship exactly as the layout spells
     * them. If that ever stops being true, assert the normalised form and say why here — do not
     * loosen this to a substring of the token name, which would make it unfalsifiable.
     *
     * Plan 042 restacked exactly these rows under container queries, which is where a dropped
     * cell is easiest to introduce and hardest to see — and split them across two drawings, one
     * of which the arms below reduce to a single line per token. See {@link paletteRowLiterals}.
     */
    it("prints each token's own two values in that token's own row", () => {
        expect(PALETTE.length, "PALETTE is empty — this gate would assert nothing")
            .toBeGreaterThan(10);
        const rows = paletteRowLiterals();
        expect(rows.length, `fewer rows parsed out of ${DESIGN_PAGE_FILE} than the palette has `
            + "tokens — one of the two drawings has stopped being found, and this gate would be "
            + "vacuous for every token it drew")
            .toBeGreaterThanOrEqual(PALETTE.length);
        expect(PALETTE.flatMap(({token, light, dark}) => {
            const row = rows.find((literals) => literals.includes(token));
            if (!row) return [`${token}: the page draws no row naming it`];
            return [light, dark].filter((v) => !row.includes(v)).map((v) => `${token}: ${v} missing`);
        }),
            `${DESIGN_PAGE_FILE} does not print these values in the row of the token they belong `
            + "to, so a reader takes a colour off /design that the browser resolves for some "
            + "other token — or takes nothing at all")
            .toEqual([]);
        expect(rows.flat().filter((t) => /^#[0-9A-Fa-f]{3,8}$/.test(t)).length,
            `${DESIGN_PAGE_FILE} draws fewer value cells than the palette has values, so a whole `
            + "column has been dropped from the row")
            .toBeGreaterThanOrEqual(PALETTE.length * 2);
    });

    /**
     * A SECTION HAS AN ADDRESS AND SOMETHING THAT GOES THERE, and both halves are needed.
     *
     * A reference document is entered from a search result at a section rather than at the top,
     * and before plan 042 this one had no addressable section at all: reaching Marks meant
     * scrolling past everything above it. The row of chips under the lede is the site's answer,
     * derived from `SECTIONS` so a section published in the module is reachable the moment it
     * exists.
     *
     * THE ID IS COUNTED, NOT MERELY FOUND. A duplicated `id` is the defect that actually breaks
     * an anchor — the second one is unreachable and the browser silently takes the first — and
     * "does the page contain this string" answers yes for a duplicate as readily as for a unique
     * one. So this counts occurrences and demands exactly one.
     *
     * THE ADDRESS IS DERIVED FROM THE KEY AND THAT IS A PUBLIC CONTRACT. A heading is prose
     * somebody may reword; a key is the module's stable identifier. Renaming one breaks every
     * bookmark pointing at that section, and there is no redirect layer on this site.
     */
    it("gives every section an address, and a chip that goes there", () => {
        const keys = Object.keys(SECTIONS) as (keyof typeof SECTIONS)[];
        expect(keys.length, "SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        const html = readFileSync(DESIGN_PAGE_FILE, "utf8");
        const occurrences = (needle: string) => html.split(needle).length - 1;
        expect(keys.map((key) => `${key}: ${occurrences(`id="design-${key}"`)}`)
            .filter((line) => !line.endsWith(": 1")),
            `${DESIGN_PAGE_FILE} must carry exactly one id="design-<key>" per section. Zero is a `
            + "chip pointing nowhere; two is an anchor a reader can only reach half of")
            .toEqual([]);
        expect(keys.filter((key) => occurrences(`href="#design-${key}"`) < 1),
            `${DESIGN_PAGE_FILE} publishes a section with no chip linking to it, so the page's own `
            + "index is shorter than the page")
            .toEqual([]);
    });

    /**
     * A KIND OF CONTROL IS DRAWN, NOT JUST NAMED. The gate above asks whether every name in
     * `CONTROLS` reaches the page as text, and a name printed in a list with nothing beside it
     * satisfies exactly that — which is the state plan 042's throw makes impossible at build time
     * and this makes impossible in the artifact.
     *
     * THE SPECIMEN IS MATCHED BY THE KIND'S OWN CLASS, in the row that names the kind, so the two
     * cannot drift apart: a row labelled `chip-icon` whose specimen wears `chip` is a specimen of
     * the wrong control, and is caught here rather than read as a pass. Class tokens are compared
     * whole for that reason — `chip` is a prefix of `chip-icon`.
     */
    it("draws a specimen for every kind of control, not just its name", () => {
        expect(CONTROLS.length, "CONTROLS is empty — this gate would assert nothing")
            .toBeGreaterThan(1);
        const html = readFileSync(DESIGN_PAGE_FILE, "utf8");
        const rows = [...html.matchAll(/<li class="design-row"[^>]*>([\s\S]*?)<\/li>/g)].map((m) => m[1]!);
        expect(rows.length, `no .design-row parsed out of ${DESIGN_PAGE_FILE} — this gate would be vacuous`)
            .toBeGreaterThanOrEqual(CONTROLS.length);
        const named = (row: string) =>
            [...row.matchAll(/<span class="[^"]*\bdesign-name\b[^"]*"[^>]*>([\s\S]*?)<\/span>/g)]
                .map((box) => collapsed(decodeEntities(box[1]!.replace(/<[^>]*>/g, ""))));
        const wears = (row: string, kind: string) =>
            [...row.matchAll(/<a\b[^>]*\sclass="([^"]*)"/g)]
                .some((a) => a[1]!.split(/\s+/).includes(kind));
        expect(CONTROLS.map(({name}) => name).filter((name) => {
            const row = rows.find((r) => named(r).includes(name));
            return !row || !wears(row, name);
        }),
            `${DESIGN_PAGE_FILE} names these kinds of control and draws no link wearing them, so `
            + "the site's own styleguide publishes a vocabulary a reader cannot see an example of")
            .toEqual([]);
    });

    /**
     * THIS PAGE INVENTS NO LABEL REGISTER, and the two it uses are read from where they are
     * declared rather than restated here.
     *
     * It had three. The site owns two — the chip's `0.75rem / 700 / 0.1em` in `uno.config.ts`, and
     * the bib's meta row at `0.625rem / 700 / 0.14em` — and `.design-guide-heading` arrived with
     * the chip's size at 0.08em of tracking, which is the chip's register with the one number
     * nobody could give a reason for changed. The page that documents the system grew the system
     * a register.
     *
     * ASSERTED AS A SET RATHER THAN AS TWO EQUALITIES, because the failure is a THIRD value
     * appearing and a pair of equalities cannot see one. Both members of the set are derived: the
     * chip's from the shortcut source, the bib's from the wall page's own shipped rule. Nothing
     * about this gate knows what either number is, which is the difference between it and the
     * `grep -c '0.08em'` that would have caught only the one register that has already gone.
     */
    it("sets every label on this page in one of the site's own two registers", () => {
        const tracking = (value: string) => value.trim().replace(/^0(?=\.)/, "");
        const chip = (unoConfig.shortcuts as Record<string, string>).chip;
        expect(typeof chip, "uno.config.ts publishes no `chip` shortcut — this gate would be vacuous")
            .toBe("string");
        const chipTracking = (chip as string).match(/tracking-\[([^\]]+)\]/)?.[1];
        expect(chipTracking, "the `chip` shortcut declares no tracking, so the register a label over "
            + "a block is set in cannot be read off it").toBeTruthy();

        const wallCss = pageCss("dist/patches/index.html");
        const bibTracking = wallCss.match(/\.bib-meta[^{]*\{[^}]*letter-spacing:\s*([^;}]+)/)?.[1];
        expect(bibTracking, "the wall ships no .bib-meta letter-spacing, so the register a specimen's "
            + "own eyebrow is set in cannot be read off it").toBeTruthy();

        const allowed = new Set([tracking(chipTracking!), tracking(bibTracking!)]);
        expect(allowed.size, "the two registers resolved to one value — this gate would allow a third "
            + "by accident").toBe(2);

        const found = [...pageCss(DESIGN_PAGE_FILE).matchAll(/letter-spacing:\s*([^;}]+)/g)]
            .map((m) => tracking(m[1]!));
        expect(found.length, `${DESIGN_PAGE_FILE} ships no letter-spacing at all — this gate would be `
            + "vacuous").toBeGreaterThan(1);
        expect([...new Set(found)].filter((v) => !allowed.has(v)).sort(),
            `${DESIGN_PAGE_FILE} sets a label in a register the site does not have. The two it may `
            + `use are ${[...allowed].join(" and ")}: the chip's, for a label over a block, and the `
            + "bib's, for a specimen's own eyebrow")
            .toEqual([]);
    });

    it("shows every type step the stylesheet ships", () => {
        const steps = new Set([...css.matchAll(/\.(text-[a-z0-9]+)\{font-size/g)].map((m) => m[1]!));
        expect(steps.size, "no type steps parsed out of the stylesheet — this gate would be vacuous")
            .toBeGreaterThan(2);
        const worn = classTokens(DESIGN_PAGE_FILE);
        expect([...steps].filter((s) => !worn.has(s)).sort(),
            `${DESIGN_PAGE_FILE} is the site's own type specimen and does not show these steps`)
            .toEqual([]);
    });
});
