import {readFileSync} from "node:fs";
import {describe, expect, it} from "vitest";

import {SECTIONS, THEMING, TOKEN_ROLES} from "../src/content/design";
import {renderDesignDoc} from "../src/lib/design-doc";
import {ICON_IDS, iconClass} from "../src/lib/icons";
import {pageCss} from "./helpers/css";
import {classTokens} from "./helpers/pages";

/**
 * THE PALETTE IS PUBLISHED SOMEWHERE THIS SUITE CANNOT SEE, AND THIS IS THE HALF THAT CAN.
 *
 * The site's design vocabulary — fifteen theme tokens, a short type ramp, three controls —
 * is synced to a design tool, where an agent builds screens out of it. That export is a
 * SNAPSHOT: it is generated by a converter that runs by hand, against the built site, and
 * nothing about editing this repository re-runs it. So the failure mode is not a bad
 * export. It is a good export going quietly out of date the moment a token is renamed here.
 *
 * The division of labour is the one `tests/dns-config.test.ts` argues for, and neither half
 * is redundant:
 *
 *   - The CONVERTER proves the export can be built and is internally consistent. It needs
 *     the design tool's own toolchain and a network round trip, so it runs when somebody
 *     syncs, and never in CI.
 *   - THIS half proves the shipped files still say what the export claims about them, and
 *     it runs in `pnpm test` on every pull request — including the ones that touch nothing
 *     under `.design-sync/`. That is the whole point: the way this breaks is an edit to
 *     `src/layouts/BasicLayout.astro`, and nothing in the sync directory would notice.
 *
 * WHAT IS ASSERTED, AND WHY EACH ONE IS HERE. `.design-sync/conventions.md` is the document
 * handed to the design agent as the system's own description of itself. Every name in it
 * was checked by hand once, at sync time, against a build that no longer exists. These
 * gates are that check made repeatable:
 *
 *   1. The two themes define the SAME tokens. This is a source-of-truth invariant that
 *      owes nothing to the sync — a token added to light and forgotten in dark resolves to
 *      nothing for every reader on the other theme, and no other gate here looks.
 *   2. The document's token table and the built stylesheet name the same set, BOTH ways. A
 *      one-way check would let the table quietly shrink.
 *   3. The classes the document promises are present really are; the one it warns is
 *      ABSENT really is. That warning is the document's most load-bearing sentence — a
 *      shortcut composed into others is not itself emitted, so an agent that believed
 *      otherwise would write markup that silently does nothing.
 *
 * It reads the built page rather than the source, through `pageCss`, because the export is
 * built from the same artifact: what ships is what the agent gets.
 *
 * WHAT CHANGED WHEN `/design` ARRIVED, because two of the gates below now point somewhere
 * else. The document stopped being hand-written: it is RENDERED from `src/content/design.ts`
 * and held against the committed copy by a file snapshot, so the question "does the markdown
 * still say what the code says" collapses into "was the file regenerated". That moves the
 * gated source one level up — the token gate reads the MODULE against the stylesheet now,
 * rather than the markdown table against the stylesheet, because the table is no longer a
 * place anyone can type into. The chain is: stylesheet defines, module names, document and
 * page render. Each link has an assertion here, and the middle one is the only one a person
 * edits.
 *
 * THE SNAPSHOT IS THE LEGITIMATE FORM OF A COMMITTED GENERATED FILE, and the distinction is
 * the whole reason four generated HTML reference cards were retired rather than kept:
 * `dns/requirements.txt` is compiled from `dns/requirements.in` and a gate fails when the two
 * disagree, where `public/preview.jpg` is a render of a card with nothing watching and has
 * gone stale silently twice. `pnpm test:update` regenerates; drift fails `pnpm test`.
 */

const CONVENTIONS = ".design-sync/conventions.md";
const conventions = () => readFileSync(CONVENTIONS, "utf8");

/** The `/design` page, as the build emits it. */
const DESIGN_PAGE_FILE = "dist/design/index.html";

/**
 * THE SPEC AT THE REPOSITORY ROOT, which is the same bytes as `/design.md` on the web.
 *
 * `DESIGN.md` is a generated file that is COMMITTED, which this repository allows in exactly one
 * shape: compiled from a named source with a gate that fails when the two disagree — the shape
 * `dns/requirements.txt` has, and the opposite of `public/preview.jpg`, which is a render of a
 * card with nothing watching and has gone stale silently twice. `pnpm test:update` regenerates;
 * drift fails `pnpm test`.
 *
 * The name is not this repository's choice. The `improve` pipeline these plans implement globs
 * for it by name during recon and carries what it finds into the plans it writes, and the
 * DESIGN.md format is an open convention for exactly this document — so a file called anything
 * else would be a file nothing looks for.
 */
const DESIGN_DOC = "DESIGN.md";

/**
 * THE BUDGET, AND IT IS NOT THIS REPOSITORY'S NUMBER.
 *
 * `.design-sync/conventions.md` is prepended to a generated README through the `readmeHeader`
 * key and inlined into the SYSTEM PROMPT of a design agent that gets that README and the bound
 * artifacts and nothing else. The design-sync skill states the preamble budget as two to four
 * thousand characters; this is the top of that range, so it is a ceiling rather than a target.
 *
 * WHY IT IS ASSERTED AND NOT WRITTEN DOWN IN PROSE. The document is generated, so its length is
 * a function of a module anybody may edit — and the failure mode is silent: a longer preamble
 * still renders, still matches its own committed copy, and simply spends more of a context
 * window that belongs to somebody else. The previous hand-written document was already over
 * this line, and the generated one that replaced it was nearly twice it.
 *
 * WHAT TO DO WHEN THIS GOES RED: drop something from the AGENT audience in
 * `src/lib/design-doc.ts`, never from `src/content/design.ts` — the full rendering carries the
 * module whole, and trimming the module would take the guidance off `/design` and out of
 * `DESIGN.md` to buy room in a third document. Record the trade in `.design-sync/NOTES.md`.
 */
const AGENT_BUDGET = 4096;

/** Every `--token: value` declared under a `:root[data-theme=…]` block in the built CSS. */
function themeTokens(css: string): Record<string, Set<string>> {
    const themes: Record<string, Set<string>> = {};
    for (const m of css.matchAll(/:root\[data-theme=['"]?(\w+)['"]?\]\s*\{([^}]*)\}/g)) {
        const names = [...m[2]!.matchAll(/(--[\w-]+)\s*:/g)].map((d) => d[1]!);
        if (!names.length) continue;
        themes[m[1]!] ??= new Set();
        for (const n of names) themes[m[1]!]!.add(n);
    }
    return themes;
}

describe("the design system this site publishes", () => {
    const css = pageCss();
    const themes = themeTokens(css);

    it("defines both themes, from the built page", () => {
        expect(Object.keys(themes).sort(),
            "the theme blocks moved or changed shape — every assertion below would be vacuous")
            .toEqual(["dark", "light"]);
        expect(themes.light!.size,
            "no tokens parsed out of the light theme — the gates below would assert nothing")
            .toBeGreaterThan(10);
    });

    it("gives every token a value in BOTH themes", () => {
        const light = [...themes.light!].sort(), dark = [...themes.dark!].sort();
        expect(dark.filter((t) => !themes.light!.has(t)),
            "these are defined in dark and not in light, so they resolve to nothing in light")
            .toEqual([]);
        expect(light.filter((t) => !themes.dark!.has(t)),
            "these are defined in light and not in dark, so they resolve to nothing in dark")
            .toEqual([]);
    });

    /**
     * THE MODULE IS THE GATED SOURCE NOW, not the markdown table.
     *
     * This used to read `.design-sync/conventions.md`'s table, because that table was where a
     * person typed a token's name. It is generated from `TOKEN_ROLES` today, so reading it
     * here would ask the same question one level too far downstream: the snapshot below
     * already proves the table IS the module, and a gate that checks a rendering of a list
     * against the stylesheet cannot say which of the two is wrong when they disagree.
     *
     * BOTH DIRECTIONS, for the reason the old note gave: a one-way check lets the list
     * quietly shrink. A token defined in the layout and never named here is one no designer
     * and no agent will ever reach for; a token named here that the stylesheet no longer
     * defines sends both of them at something that resolves to nothing.
     */
    it("names every token the stylesheet defines, and no other", () => {
        const named = new Set(TOKEN_ROLES.map((t) => t.token));
        expect(named.size, "TOKEN_ROLES is empty — this gate would assert nothing")
            .toBe(TOKEN_ROLES.length);
        const defined = themes.light!;
        expect([...defined].filter((t) => !named.has(t)).sort(),
            "src/content/design.ts gives these tokens no role, so nothing that reads it will reach for them")
            .toEqual([]);
        expect([...named].filter((t) => !defined.has(t)).sort(),
            "src/content/design.ts names these and the built stylesheet does not define them")
            .toEqual([]);
    });

    it("ships the classes that document promises are present", () => {
        const doc = conventions();
        const promised = doc.match(/Guaranteed present: ([^.]+)\./s)?.[1];
        expect(promised, `${CONVENTIONS} no longer carries its "Guaranteed present" list`).toBeTruthy();
        const names = [...promised!.matchAll(/`([a-z][\w-]*)`/g)].map((m) => m[1]!);
        expect(names.length, "no class names parsed out of that list — this gate would be vacuous")
            .toBeGreaterThan(3);
        expect(names.filter((n) => !css.includes(`.${n}{`)),
            `${CONVENTIONS} promises these classes and the built stylesheet has no rule for them`)
            .toEqual([]);
    });

    it("keeps the one class that document warns is absent absent", () => {
        expect(conventions()).toContain("`control-surface` is not in the stylesheet");
        expect(css.includes(".control-surface{"),
            "`control-surface` now ships a rule, so the warning in " + CONVENTIONS + " is false")
            .toBe(false);
    });

    /**
     * EACH COMMITTED DOCUMENT IS THE RENDERING, and this is what makes that checkable rather
     * than a convention. Edit a role in `src/content/design.ts` and these go red until
     * `pnpm test:update` rewrites the files; edit a file by hand and it goes red until the
     * edit is moved into the module. Both directions are the point — the second one is what
     * `.design-sync/NOTES.md` used to have to ask for in prose.
     *
     * TWO SNAPSHOTS OF ONE RENDERER, and the pair is the whole reason `renderDesignDoc` takes an
     * audience instead of there being two functions. A second renderer would drift from the
     * first in silence: both would still render, and both would still match their own committed
     * copy, because a snapshot only ever compares a document with itself.
     */
    it("is the module, rendered — the agent's document has no second author", async () => {
        await expect(renderDesignDoc("agent")).toMatchFileSnapshot(`../${CONVENTIONS}`);
    });

    it("is the module, rendered in full — the repository's spec has no second author", async () => {
        await expect(renderDesignDoc("full")).toMatchFileSnapshot(`../${DESIGN_DOC}`);
    });

    /**
     * THE BUDGET IS THE ONE PROPERTY THE SNAPSHOT ABOVE CANNOT SEE. A document twice its size
     * matches its own committed copy perfectly; the cost lands in a context window belonging to
     * a design agent that never gets to complain. See `AGENT_BUDGET` for where the number comes
     * from and for what to do when this goes red.
     */
    it("keeps the agent's preamble inside the budget it is inlined into", () => {
        const rendered = renderDesignDoc("agent");
        expect(rendered.length,
            `the agent rendering is ${rendered.length} characters against a ${AGENT_BUDGET} budget. It is `
            + `inlined into a design agent's system prompt, so this is somebody else's context window `
            + `being spent. Drop something from the "agent" audience in src/lib/design-doc.ts — never `
            + `from src/content/design.ts, which the full rendering carries whole — and record the `
            + `trade in .design-sync/NOTES.md`)
            .toBeLessThanOrEqual(AGENT_BUDGET);
    });

    /**
     * THE AGENT CANNOT OPEN THIS REPOSITORY, so a path into it is not a weak pointer — it is a
     * dead end dressed as an instruction. That agent "gets the README and the bound artifacts,
     * nothing else", which is why the closed-set section sends it to the stylesheet it was handed
     * rather than to the layout the tokens are actually declared in.
     *
     * THE FULL RENDERING IS ASSERTED IN THE OPPOSITE DIRECTION in the same breath, because a
     * predicate that only ever says "no" is satisfied by an empty string. Its readers both have
     * this tree open — one is reading `DESIGN.md` in a checkout, the other fetched `/design.md`
     * from a site whose source is public — so pointing at a file is the useful thing to do, and a
     * full rendering that had stopped doing it would be the same defect from the other side.
     */
    it("sends the agent to the bundle and the checkout reader to the tree", () => {
        expect(renderDesignDoc("agent"),
            "the agent rendering names a path in this repository, which its reader has no copy of")
            .not.toMatch(/\bsrc\//);
        expect(renderDesignDoc("full"),
            "the full rendering names no path in this repository, so it tells a reader holding the "
            + "checkout nothing about where any of this is written down")
            .toMatch(/\bsrc\//);
    });

    /**
     * NEITHER RENDERING MAY GO EMPTY, which is the one way a snapshot can be passed by a document
     * that says nothing: delete the body, run `pnpm test:update`, and both files agree perfectly
     * with a renderer that produces two headings. So each is asked for the thing it exists to
     * carry — every token the module names — and the two are asked separately, because they are
     * two audiences and a union would let either one shrink to nothing behind the other.
     */
    it("carries every token the module names, in both renderings", () => {
        expect(TOKEN_ROLES.length, "TOKEN_ROLES is empty — this gate would assert nothing")
            .toBeGreaterThan(5);
        for (const audience of ["full", "agent"] as const) {
            const rendered = renderDesignDoc(audience);
            expect(rendered.length, `the ${audience} rendering is empty`).toBeGreaterThan(500);
            expect(TOKEN_ROLES.map(({token}) => token).filter((t) => !rendered.includes(t)),
                `the ${audience} rendering does not name these tokens, so whatever reads it cannot `
                + "reach for them").toEqual([]);
        }
    });

    /**
     * A HEADING WITH NOTHING UNDER IT IS THE ONE FAILURE THE SNAPSHOT CANNOT SEE, because an
     * empty list renders as an empty list and matches its own committed copy perfectly. The
     * guidance is the half of this module a design agent actually acts on, so a section that
     * has stopped carrying any is worth more than a heading that has gone missing.
     */
    it("gives every section guidance on both sides", () => {
        const sections = Object.entries(SECTIONS);
        expect(sections.length, "SECTIONS is empty — this gate would assert nothing").toBeGreaterThan(0);
        for (const [key, section] of sections) {
            expect(section.does.length, `SECTIONS.${key} tells nobody what to do`).toBeGreaterThan(0);
            expect(section.donts.length, `SECTIONS.${key} tells nobody what not to do`).toBeGreaterThan(0);
            expect(section.heading.trim().length, `SECTIONS.${key} has no heading`).toBeGreaterThan(0);
            expect(section.lede.trim().length, `SECTIONS.${key} has no lede`).toBeGreaterThan(0);
        }
    });

    /**
     * THE RAMP ON THE PAGE IS A CENSUS AND THIS IS ITS GATE.
     *
     * `src/pages/design.astro` has to write its type steps out as literal class names, because
     * UnoCSS only emits a rule for a name it can see literally in a file it scans and it does
     * not scan `.ts` — the same fact the icon safelist exists for. A written-out list is a
     * second copy of a set the stylesheet already owns, so it needs the thing every other
     * census in this repository has: something that reddens when the two disagree.
     *
     * ASKED IN THE DIRECTION THAT CAN ACTUALLY BE WRONG. A step the page shows and no other
     * page uses is not a defect — the page is a legitimate wearer, and its own use is what
     * puts the rule in the sheet. A step some OTHER page wears and this one omits is a
     * styleguide that has quietly stopped describing the site, and that is what this catches.
     */
    /**
     * THE CENSUS IS COMPLETE, WHICH IS A STRONGER CLAIM THAN THE SAFELIST EVER NEEDED.
     *
     * `ICON_IDS` exists so `uno.config.ts` can emit a rule for every mark that is computed at
     * render time. That job never required it to be exhaustive: the theme toggle writes its
     * sun and moon out as literal class names, UnoCSS extracts them by itself, and the
     * safelist was complete without them for as long as nothing else read it.
     *
     * `/design` reads it, and reads it as "the marks a designer may reach for" — so the list
     * has to answer a question it was never asked before. Measured before this gate went in:
     * the page rendered 16 of the 18 marks the build ships and the generated document told a
     * design agent that 16 was the whole set. Both halves are asserted here, because either
     * one alone permits the defect: a mark in the sheet and not in the census is a mark
     * nothing describes, and a mark in the census with no rule is the zero-size mask box the
     * safelist exists to prevent.
     */
    /**
     * THE THEME NAMES ARE THE ONE VALUE THIS MODULE RESTATES, so they are gated rather than
     * trusted.
     *
     * `THEMING.themes` exists because both surfaces need the legal set: `/design` renders the
     * line matching the live theme and hides the other, and the generated document lists both
     * for an agent that has neither. The names themselves belong to
     * `src/layouts/BasicLayout.astro`, which is where the two `:root[data-theme=…]` blocks are
     * — so this list is a second home, and a second home nothing checks is the exact defect
     * this whole suite exists for.
     *
     * BOTH DIRECTIONS. A theme in the stylesheet and not in this list is a page that would
     * render NO example line for a reader in it; a theme in the list and not in the stylesheet
     * is a value the document tells a designer to write that resolves to nothing.
     */
    it("names every theme the stylesheet defines, and no other", () => {
        const declared = Object.keys(themes).sort();
        expect(declared.length, "no theme blocks parsed — this gate would assert nothing")
            .toBeGreaterThan(1);
        expect([...THEMING.themes].sort(),
            "src/content/design.ts's theme list and the built stylesheet's theme blocks disagree, so "
            + "/design would render the wrong example line — or none at all — for a reader in the "
            + "theme it has forgotten")
            .toEqual(declared);
        expect(THEMING.example.includes("{theme}"),
            "THEMING.example lost its {theme} placeholder, so both surfaces would print it literally")
            .toBe(true);
    });

    it("names every mark the build ships, and no mark the build does not", () => {
        const shipped = new Set([...css.matchAll(/\.(i-[a-z0-9-]+)/g)].map((m) => m[1]!));
        expect(shipped.size, "no icon rules parsed out of the stylesheet — this gate would be vacuous")
            .toBeGreaterThan(5);
        const census = new Set(ICON_IDS.map(iconClass));
        expect([...shipped].filter((c) => !census.has(c)).sort(),
            "the stylesheet ships these marks and ICON_IDS does not name them, so /design and the "
            + "document generated from it both understate what a designer may reach for")
            .toEqual([]);
        expect([...census].filter((c) => !shipped.has(c)).sort(),
            "ICON_IDS names these and the stylesheet has no rule for them — a presetIcons class with "
            + "no rule renders as a mask box at zero size")
            .toEqual([]);
    });

    it("shows every type step the stylesheet ships", () => {
        const steps = new Set([...css.matchAll(/\.(text-[a-z0-9]+)\{font-size/g)].map((m) => m[1]!));
        expect(steps.size, "no type steps parsed out of the stylesheet — this gate would be vacuous")
            .toBeGreaterThan(2);
        const worn = classTokens(DESIGN_PAGE_FILE);
        expect([...steps].filter((s) => !worn.has(s)).sort(),
            `${DESIGN_PAGE_FILE} is the site's own type specimen and does not show these steps`)
            .toEqual([]);
    });
});
