import {readFileSync} from "node:fs";
import {describe, expect, it} from "vitest";

import {pageCss} from "./helpers/css";

/**
 * THE PALETTE IS PUBLISHED SOMEWHERE THIS SUITE CANNOT SEE, AND THIS IS THE HALF THAT CAN.
 *
 * The site's design vocabulary — fifteen theme tokens, a short type ramp, three controls —
 * is synced to a design tool, where an agent builds screens out of it. That export is a
 * SNAPSHOT: it is generated by a converter that runs by hand, against the built site, and
 * nothing about editing this repository re-runs it. So the failure mode is not a bad
 * export. It is a good export going quietly out of date the moment a token is renamed here.
 *
 * The division of labour is the one `tests/dns-config.test.ts` argues for, and neither half
 * is redundant:
 *
 *   - The CONVERTER proves the export can be built and is internally consistent. It needs
 *     the design tool's own toolchain and a network round trip, so it runs when somebody
 *     syncs, and never in CI.
 *   - THIS half proves the shipped files still say what the export claims about them, and
 *     it runs in `pnpm test` on every pull request — including the ones that touch nothing
 *     under `.design-sync/`. That is the whole point: the way this breaks is an edit to
 *     `src/layouts/BasicLayout.astro`, and nothing in the sync directory would notice.
 *
 * WHAT IS ASSERTED, AND WHY EACH ONE IS HERE. `.design-sync/conventions.md` is the document
 * handed to the design agent as the system's own description of itself. Every name in it
 * was checked by hand once, at sync time, against a build that no longer exists. These
 * gates are that check made repeatable:
 *
 *   1. The two themes define the SAME tokens. This is a source-of-truth invariant that
 *      owes nothing to the sync — a token added to light and forgotten in dark resolves to
 *      nothing for every reader on the other theme, and no other gate here looks.
 *   2. The document's token table and the built stylesheet name the same set, BOTH ways. A
 *      one-way check would let the table quietly shrink.
 *   3. The classes the document promises are present really are; the one it warns is
 *      ABSENT really is. That warning is the document's most load-bearing sentence — a
 *      shortcut composed into others is not itself emitted, so an agent that believed
 *      otherwise would write markup that silently does nothing.
 *
 * It reads the built page rather than the source, through `pageCss`, because the export is
 * built from the same artifact: what ships is what the agent gets.
 */

const CONVENTIONS = ".design-sync/conventions.md";
const conventions = () => readFileSync(CONVENTIONS, "utf8");

/** Every `--token: value` declared under a `:root[data-theme=…]` block in the built CSS. */
function themeTokens(css: string): Record<string, Set<string>> {
    const themes: Record<string, Set<string>> = {};
    for (const m of css.matchAll(/:root\[data-theme=['"]?(\w+)['"]?\]\s*\{([^}]*)\}/g)) {
        const names = [...m[2]!.matchAll(/(--[\w-]+)\s*:/g)].map((d) => d[1]!);
        if (!names.length) continue;
        themes[m[1]!] ??= new Set();
        for (const n of names) themes[m[1]!]!.add(n);
    }
    return themes;
}

describe("the design system this site publishes", () => {
    const css = pageCss();
    const themes = themeTokens(css);

    it("defines both themes, from the built page", () => {
        expect(Object.keys(themes).sort(),
            "the theme blocks moved or changed shape — every assertion below would be vacuous")
            .toEqual(["dark", "light"]);
        expect(themes.light!.size,
            "no tokens parsed out of the light theme — the gates below would assert nothing")
            .toBeGreaterThan(10);
    });

    it("gives every token a value in BOTH themes", () => {
        const light = [...themes.light!].sort(), dark = [...themes.dark!].sort();
        expect(dark.filter((t) => !themes.light!.has(t)),
            "these are defined in dark and not in light, so they resolve to nothing in light")
            .toEqual([]);
        expect(light.filter((t) => !themes.dark!.has(t)),
            "these are defined in light and not in dark, so they resolve to nothing in dark")
            .toEqual([]);
    });

    it("names every token in the document the design agent is handed, and no other", () => {
        // The TABLE, not the whole document. Scoping this to backticks anywhere was a
        // predicate wider than the property the prose claims, and it proved it: deleting a
        // row for a token the surrounding do/don'ts also mention left the gate green.
        const rows = conventions().split("\n").filter((l) => /^\s*\|/.test(l));
        expect(rows.length, "no table rows found — this gate would assert nothing").toBeGreaterThan(5);
        const named = new Set([...rows.join("\n").matchAll(/`(--[\w-]+)`/g)].map((m) => m[1]!));
        const defined = themes.light!;
        expect([...defined].filter((t) => !named.has(t)).sort(),
            `${CONVENTIONS}'s token table is missing these, so the agent will never reach for them`)
            .toEqual([]);
        expect([...named].filter((t) => !defined.has(t)).sort(),
            `${CONVENTIONS}'s token table names these and the built stylesheet does not define them`)
            .toEqual([]);
    });

    it("ships the classes that document promises are present", () => {
        const doc = conventions();
        const promised = doc.match(/Guaranteed present: ([^.]+)\./s)?.[1];
        expect(promised, `${CONVENTIONS} no longer carries its "Guaranteed present" list`).toBeTruthy();
        const names = [...promised!.matchAll(/`([a-z][\w-]*)`/g)].map((m) => m[1]!);
        expect(names.length, "no class names parsed out of that list — this gate would be vacuous")
            .toBeGreaterThan(3);
        expect(names.filter((n) => !css.includes(`.${n}{`)),
            `${CONVENTIONS} promises these classes and the built stylesheet has no rule for them`)
            .toEqual([]);
    });

    it("keeps the one class that document warns is absent absent", () => {
        expect(conventions()).toContain("`control-surface` is not in the stylesheet");
        expect(css.includes(".control-surface{"),
            "`control-surface` now ships a rule, so the warning in " + CONVENTIONS + " is false")
            .toBe(false);
    });
});
